version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 2G  # Vite требует памяти для сборки