version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: your-frontend-image:${TAG:-latest}
    ports:
      - "80:80"  # Используем только 80 порт
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - frontend-net
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  frontend-net:
    driver: bridge
    attachable: false  # Повышаем безопасность