version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "3000:3000"
