name: Deploy React App to Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            PROJECT_DIR="/home/ubuntu/B2B-Printgrad"
            REPO_URL="git@github.com:Veterjaike/B2B-Printgrad.git"

            if [ ! -d "$PROJECT_DIR" ]; then
              echo "Project directory not found, cloning repo..."
              git clone "$REPO_URL" "$PROJECT_DIR"
            else
              echo "Project directory found, pulling latest changes..."
              cd "$PROJECT_DIR"
              git pull origin main
            fi

            cd "$PROJECT_DIR"
            docker compose down
            docker compose up -d --build
            